### ISSUE TITLE
Can this library support Android 10 and other questions?

### ISSUE THREAD

**Issue by ctaihua** [kuromadara/direct_caller_sim_choice#2]
I assign the sim no '2 'in the makePhoneCall api and  make a phone call.  
The device still use the sim 1 to start a call. (Android 10) 
However, I use the same app in another phone (Android 12), It doesn't.
Does this lib support Android 10?
Can you tell me your Android env and flutter version for this lib?

Thank you!!!

**Comment by kuromadara** [comment]
Hello there that is a known bug that i'm unable to solve. I'm using android 11 (Poco F1) and android 12 (Samsung) I also found the issue in the samsung device a  default sim doesnot work i have to choose a sim in the samsung device by myself. 

Thank you
