### ISSUE TITLE
Can you tell me your testing environment (eg, Android version..) and mobile device?

### ISSUE THREAD

**Issue by ctaihua** [kuromadara/direct_caller_sim_choice#3]
Hello,
What are your testing env and device, I will try to have the same , simulate or different one to test your lib.
I will share my testing result and We can keep forward together.

Regards,
Philip Chen

**Comment by kuromadara** [comment]
Hello,

My testing env is: Android 11, Android 12, device: Poco F1 , Samsung (I forgot the mobile). There is a known issue when i provide default sim it doesn't work. There was some issue in the Samsung device which i forgot now.

Regards 
Dayananda Dowarah
